### PR TITLE
Update MobileFuse SDK to v1.7.3

### PR DESCRIPTION
**Pull request by tomaszbmf**
Update MobileFuse SDK to v1.7.3

### CODE REVIEW

**Review by cb-jpadilla — APPROVED** [review]
Looks good. Approved. ✔️

**Review by bichenwang — APPROVED** [review]
I'll make the adapter cert build

**Comment by CB-RyanMcCormick** [comment]
Hi, @tomaszbmf, I'm trying to test this change using the firebase build from this PR and I'm constantly getting instant 204 responses from our ad server. Are there special instructions for testing this?

**Comment by davefmf** [comment]
hi @CB-RyanMcCormick,

Dave from the MobileFuse engineering team here! I have connected with Ana from your team on Slack with detailed information, logs etc. I don't believe there's anything special required to test it as we have had success before.

**Pull request merged**
